<div class="loadingio-spinner-blocks-gqqvuy7uy0c">
	<div class="ldio-zpp3oj9i7h">
		<div style="left:38px;top:38px;animation-delay:0s" />
		<div style="left:80px;top:38px;animation-delay:0.125s" />
		<div style="left:122px;top:38px;animation-delay:0.25s" />
		<div style="left:38px;top:80px;animation-delay:0.875s" />
		<div style="left:122px;top:80px;animation-delay:0.375s" />
		<div style="left:38px;top:122px;animation-delay:0.75s" />
		<div style="left:80px;top:122px;animation-delay:0.625s" />
		<div style="left:122px;top:122px;animation-delay:0.5s" />
	</div>
</div>

<style>
	@keyframes ldio-zpp3oj9i7h {
		0% {
			background: #f8b26a;
		}
		12.5% {
			background: #f8b26a;
		}
		12.625% {
			background: #e15b64;
		}
		100% {
			background: #e15b64;
		}
	}
	.ldio-zpp3oj9i7h div {
		position: absolute;
		width: 40px;
		height: 40px;
		background: #e15b64;
		animation: ldio-zpp3oj9i7h 1s linear infinite;
	}
	.loadingio-spinner-blocks-gqqvuy7uy0c {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		background: transparent;
	}
	.ldio-zpp3oj9i7h {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-zpp3oj9i7h div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
